"""add Exercise and PaperQuestionScore

Revision ID: c824abe2175e
Revises: 
Create Date: 2018-08-24 13:36:19.619587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c824abe2175e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('begin_time', sa.DateTime(), nullable=True),
    sa.Column('question_list', sa.Text(), nullable=True),
    sa.Column('result_list', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('paper_question_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pq_score', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('paperquestion')
    op.add_column('mistakes', sa.Column('correct_times', sa.Integer(), nullable=False))
    op.add_column('scores', sa.Column('result_list', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scores', 'result_list')
    op.drop_column('mistakes', 'correct_times')
    op.create_table('paperquestion',
    sa.Column('paper_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], name='paperquestion_ibfk_1'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='paperquestion_ibfk_2'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('paper_question_scores')
    op.drop_table('exercises')
    # ### end Alembic commands ###
